updated with list

diff --git a/.github/workflows/DeployAKS.yml b/.github/workflows/DeployAKS.yml
--- a/.github/workflows/DeployAKS.yml
+++ b/.github/workflows/DeployAKS.yml
@@ -15,47 +15,58 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3.1.0
-        
-      - name: 'Az CLI login'
-        uses: azure/login@v1
-        with:
-          client-id: ${{ secrets.AZURE_CLIENT_ID }}
-          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-  
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2.0.2
-        with:
-          terraform_version: latest
-          cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }}
-
-      - name: Terraform Init
-        id: init
-        run: terraform init
       
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate
+      - uses: azure/login@v2
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan
-        continue-on-error: true
+      - name: Azure CLI script
+        uses: azure/CLI@v1
+        with:
+          azcliversion: latest
+          inlineScript: |
+            az account show
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: 'Az CLI login'
+      #   uses: azure/login@v1
+      #   with:
+      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
+      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v2.0.2
+      #   with:
+      #     terraform_version: latest
+      #     cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }}
 
-      - name: Terraform Apply
-        run: terraform apply -auto-approve
+      # - name: Terraform Init
+      #   id: init
+      #   run: terraform init
+      
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate
 
-      - name: Terraform Output
-        run: terraform output
+      # - name: Terraform Plan
+      #   id: plan
+      #   run: terraform plan
+      #   continue-on-error: true
 
-      - name: Deploy Application
-        run: |
-         az aks get-credentials -n "cluster-bursting-jennet" -g "rg-refined-swine"
-         kubectl apply -f ./AKSApp/aks-store-quickstart.yaml
-         sleep 40
-         kubectl get service store-front
-         rm -rf ~/.kube
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      # - name: Terraform Apply
+      #   run: terraform apply -auto-approve
+
+      # - name: Terraform Output
+      #   run: terraform output
+
+      # - name: Deploy Application
+      #   run: |
+      #    az aks get-credentials -n "cluster-bursting-jennet" -g "rg-refined-swine"
+      #    kubectl apply -f ./AKSApp/aks-store-quickstart.yaml
+      #    sleep 40
+      #    kubectl get service store-front
+      #    rm -rf ~/.kube
